line-length = 120
indent-width = 4

target-version = "py312"

[lint]
select = [
    "A",  # flake8-builtins https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "ANN",  # flake8-annotations https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    "ARG",  # flake8-unused-arguments https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg
    "ASYNC",  # flake8-async https://docs.astral.sh/ruff/rules/#flake8-async-async
    "B",  # flake8-bugbear https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "BLE",  # flake8-blind-except https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble
    "C4",  # flake8-comprehensions https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "C90",  # mccabe https://docs.astral.sh/ruff/rules/#mccabe-c90
    "COM",  # flake8-commas https://docs.astral.sh/ruff/rules/#flake8-commas-com
    "E",  # pycodestyle Error https://docs.astral.sh/ruff/rules/#error-e
    "ERA",  # eradicate https://docs.astral.sh/ruff/rules/#eradicate-era
    "F",  # Pyflakes https://docs.astral.sh/ruff/rules/#pyflakes-f
    "FAST",  # FastAPI https://docs.astral.sh/ruff/rules/#fastapi-fast
    "FBT",  # flake8-boolean-trap https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt
    "FIX",  # flake8-fixme https://docs.astral.sh/ruff/rules/#flake8-fixme-fix
    "FLY",  # flynt https://docs.astral.sh/ruff/rules/#flynt-fly
    "FURB",  # refurb https://docs.astral.sh/ruff/rules/#refurb-furb
    "I",  # isort https://docs.astral.sh/ruff/rules/#isort-i
    "INP",  # flake8-no-pep420 https://docs.astral.sh/ruff/rules/#flake8-no-pep420-inp
    "ISC",  # flake8-implicit-str-concat https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc
    "LOG",  # flake8-logging https://docs.astral.sh/ruff/rules/#flake8-logging-log
    "N",  # pep8-naming https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "PERF",  # Perflint https://docs.astral.sh/ruff/rules/#perflint-perf
    "PGH",  # pygrep-hooks https://docs.astral.sh/ruff/rules/#pygrep-hooks-pgh
    "PIE",  # flake8-pie https://docs.astral.sh/ruff/rules/#flake8-pie-pie
    "PL",  # Pylint https://docs.astral.sh/ruff/rules/#pylint-pl
    "PT",  # flake8-pytest-style https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt
    # "PTH",  # flake8-use-pathlib https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "Q",  # flake8-quotes https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "RET",  # flake8-return https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "RSE",  # flake8-raise https://docs.astral.sh/ruff/rules/#flake8-raise-rse
    "RUF",  # Ruff-specific rules https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    # "S",  # flake8-bandit https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    "SIM",  # flake8-simplify https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "SLF",  # flake8-self https://docs.astral.sh/ruff/rules/#flake8-self-slf
    "T10",  # flake8-debugger https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
    "T20",  # flake8-print https://docs.astral.sh/ruff/rules/#flake8-print-t20
    "TD",  # flake8-todos https://docs.astral.sh/ruff/rules/#flake8-todos-td
    "TID",  # flake8-tidy-imports https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid
    "TRY",  # tryceratops https://docs.astral.sh/ruff/rules/#tryceratops-try 
    "UP",  # pyupgrade https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "W",  # pycodestyle Warning https://docs.astral.sh/ruff/rules/#warning-w
]

ignore = [
    "RUF002",  # ambiguous-unicode-character-docstring
    "COM812",  # missing-trailing-comma
    "TRY003",  # raise-vanilla-args
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-args = 10

[lint.per-file-ignores]
"tests/**" = [
    "PLR2004",  # Magic value used in comparison
    "SLF001",  # Private member access
]

[format]
quote-style = "single"
indent-style = "space"
