name: Main CI

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the latest version of ruff
      uses: astral-sh/ruff-action@v3
      with:
        version: "latest"
    - name: Analyzing the code with ruff
      run: |
        ruff check tests/
        ruff check app/
        ruff format --check tests/
        ruff format --check app/

  static_analyzing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv with all available options
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
        activate-environment: "true"
        python-version: ${{ matrix.python-version }}
    - name: Install project deps
      run: uv sync --all-groups
    - name: Analyzing the code with mypy
      run: |
        mypy app/


  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv with all available options
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"
        activate-environment: "true"
        python-version: ${{ matrix.python-version }}
    - name: Install project deps
      run: uv sync --all-groups
    - name: Run tests
      run: pytest tests
